[package]
name = "vec-array"
version = "0.1.0"
authors = ["SamuelFischerCode"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
